### PR TITLE
Add Planq

### PR DESCRIPTION
**Pull request by jackie-planq**
$ yarn validate cosmos/planq_7070.json
yarn run v1.22.19
$ ts-node src/index.ts cosmos/planq_7070.json
Done in 5.21s.

### CODE REVIEW

**Comment by HeesungB** [comment]
@jackie-planq Thank you for contribution!

**Comment by jackie-planq** [comment]
@HeesungB When will it be visible on https://chains.keplr.app/?
Is there a possibility to get Planq native on Keplr?

**Comment by HeesungB** [comment]
@jackie-planq  You can see on https://chains.keplr.app/
If you already add chain in Keplr, You can't see on https://chains.keplr.app/.

**Comment by jackie-planq** [comment]
@HeesungB Thanks!
Is there a possibility to get Planq native on Keplr?

**Comment by HeesungB** [comment]
@jackie-planq Could you contact the partnership department? https://keplr.crunch.help/en/

**Pull request merged**
