### PR TITLE
feat: add Artela Network testnet info.

### PR DESCRIPTION
**Pull request by 0xYuan90**
**Artela Website:** https://artela.network/
**Artela Docs:** https://docs.artela.network/main
**Artela Twitter:** https://twitter.com/Artela_Network

### CODE REVIEW

**Comment by HeesungB** [comment]
@0xYuan90 Hello.
Could you check your chain identifier?
```
Chain identifier unmatched: (expected: artela_11822, actual: artela-testnet)
```

**Comment by 0xYuan90** [comment]
hi @HeesungB , thank you so much, I will update it now

**Comment by 0xYuan90** [comment]
hi @HeesungB , please check, thanks❤️

**Comment by editaahn** [comment]
Hi, I'm closing this PR for now. Please feel free to submit a new request if needed.

**Pull request closed without merging**
