### PR TITLE
add IBCX & stIBCX

### PR DESCRIPTION
**Pull request by gnujoow**
this pr describing adding IBCX and stIBCX to the list. You can find more information about them at https://index.ion.wtf/ .

Kindly take note of the following details ;) : 
- Please note that stIBCX does not currently have a 'coinGeckoId'. I will submit another PR once it becomes available.
- Since IBCX and stIBCX are factory tokens, their image names include a path divider `/`. You can find them in the relative paths.

### CODE REVIEW

**Comment by gnujoow** [comment]
Please let me know if the image size does not meet the required standards.

**Comment by Thunnini** [comment]
@gnujoow Image size should be 256x256

**Comment by Thunnini** [comment]
이미지 파일 이름이 uibcx.png.png 이렇게 실수로 확장자 두번 들어간 것 같은데 수정해주세욤

**Comment by gnujoow** [comment]
@Thunnini 수정했습니다!

**Comment by Thunnini** [comment]
@gnujoow 이미지 사이즈가 250x250이라 테스트 실패했어요 ㅜㅜ

**Pull request merged**
