### PR TITLE
Add tucana birdee-1 testnet

### PR DESCRIPTION
**Pull request by garymeso**

### CODE REVIEW

**Comment by garymeso** [comment]
HI @editaahn , this PR is ready to review, could you review it? Thank you.

**Comment by garymeso** [comment]
Hi @editaahn , why the validation job shows `Invalid image url: https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/tucana/chain.png`?  It will be available after merge. You may check through the github content url of my forked repo: https://raw.githubusercontent.com/garymeso/keplr-chain-registry/add-tucana-birdee-testnet/images/tucana/chain.png

**Comment by editaahn** [comment]
Hi! Sorry for the late response. You should update the image directory following the json file name. Also, please make sure the image size is 256 * 256px.

**Comment by garymeso** [comment]
OK, thank you for the reminding.  Image updated, please re-trigger the validation job again, thank you. @editaahn

**Comment by editaahn** [comment]
Seems like you didn't change the name of the image directory to burdee

**Comment by garymeso** [comment]
Is it a new rule? I noticed there are some testnets chains use the same image as their mainnets, e.g. https://github.com/chainapsis/keplr-chain-registry/blob/main/cosmos/theta-testnet.json.

Fixed. Please review again thanks.

**Pull request merged**
