### PR TITLE
Update Gravity-Bridge currencies

### PR DESCRIPTION
**Pull request by ChristianBorst**

### CODE REVIEW

**Comment by HeesungB** [comment]
@ChristianBorst Hello.
It must first be added to currencies in order to be added to fee currencies.

**Comment by ChristianBorst** [comment]
@HeesungB I have fixed the discrepancies, hopefully the Github Actions succeed this time.

**Comment by ChristianBorst** [comment]
Hello @HeesungB , it appears that the validation check for Gravity-Bridge currencies is the limiter here. We explicitly want bridged currencies to appear in the wallet as having a value, e.g. USDC should always display around $1 US in value. To accomplish this, I have removed this check from src/validate.ts:

```
    if (currency.coinMinimalDenom.startsWith("gravity0x")) {
      throw new Error(
        `Do not provide bridged currency to currencies: ${currency.coinMinimalDenom}`,
      );
    }    
```

I am happy to work with you on this if there is a better way.

**Comment by HeesungB** [comment]
@ChristianBorst Could you resolve conflict?

**Comment by ChristianBorst** [comment]
@HeesungB The conflict should be resolved.

**Pull request closed without merging**
