### PR TITLE
Add TNKR token to Composable

### PR DESCRIPTION
**Pull request by arrudagates**
This PR adds the TNKR token to the currencies list of Composable (Centauri).

### CODE REVIEW

**Comment by arrudagates** [comment]
The failed check returned error `Failed to fetch coinGeckoId tinkernet from coin gecko`, I'm assuming this fails if the token does not have a price source, because it is a valid coingecko id: https://www.coingecko.com/en/coins/tinkernet

**Comment by HeesungB** [comment]
@arrudagates Hello.
It'll be able to add it once pricing is available, but it's currently in `Preview Only`.
And how can I query if the token exists?

**Comment by HeesungB** [comment]
@arrudagates Could you remove `coingeckoid`?

**Comment by editaahn** [comment]
Hi, I'm closing this PR for now. Please feel free to submit a new request if needed.

**Pull request closed without merging**
