### PR TITLE
add GODDARD to Neutron currencies

### PR DESCRIPTION
**Pull request by goddardneutron**

### CODE REVIEW

**Comment by HeesungB** [comment]
@goddardneutron Please add an image like the link example below.

`{chiainIdentifier}/{factory token minimal denom}/{minimal denom}.png`

https://github.com/chainapsis/keplr-chain-registry/tree/main/images/osmosis/factory/osmo14klwqgkmackvx2tqa0trtg69dmy0nrg4ntq4gjgw2za4734r5seqjqm4gm

**Comment by goddardneutron** [comment]
GODDARD Update @HeesungB

**Comment by HeesungB** [comment]
@goddardneutron Could you add `,` on the back of `coinImageUrl` 

```
// yours
"coinImageUrl": "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/neutron/gdd.png"

// have to fix like this
"coinImageUrl": "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/neutron/gdd.png",
```

**Comment by goddardneutron** [comment]
GODDARD Update @HeesungB

**Comment by goddardneutron** [comment]
Hello @HeesungB

**Comment by HeesungB** [comment]
@goddardneutron Could you check image file?
There is no eclip.png file.
```
https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/neutron/eclip.png
```

**Comment by goddardneutron** [comment]
Check @HeesungB

**Pull request merged**
