### PR TITLE
Add EntryPoint public testnet to registry

### PR DESCRIPTION
**Pull request by dillu24**

### CODE REVIEW

**Comment by HeesungB** [comment]
@dillu24   Hello. 
Can you edit the file using the link below?
https://github.com/chainapsis/keplr-chain-registry#requirement-details

You can also use the command below to check the validation locally.
```
yarn validate cosmos/entrypoint-pubtest.json
```

**Comment by dillu24** [comment]
> @dillu24 Hello. Can you edit the file using the link below? https://github.com/chainapsis/keplr-chain-registry#requirement-details
> 
> You can also use the command below to check the validation locally.
> 
> ```
> yarn validate cosmos/entrypoint-pubtest.json
> ```

Hey Heesung B .. thanks for your reply. I will have a look.

**Comment by HeesungB** [comment]
@dillu24 Could you check websocket?

**Comment by dillu24** [comment]
Hey @HeesungB our infra team is on it. Will get back to you once they solve this.

**Comment by dillu24** [comment]
Hey @HeesungB should be sorted now. Validation passes successfully locally.

**Pull request merged**
