### PR TITLE
Add ICS Provider

### PR DESCRIPTION
**Pull request by chalabi2**

### CODE REVIEW

**Comment by HeesungB** [comment]
@chalabi2 Could you add chain image? Each chain requires an image.

**Comment by chalabi2** [comment]
It is the cosmoshub provider testnet so I left the image the same, not sure why the validation check errors.

**Comment by HeesungB** [comment]
@chalabi2 
When validating a chain image URL, we validate that the chain image exists inside the identifier directory for that chain.

Your chain identifier is `provider` and your chain image URL is "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/cosmoshub/chain.png".

You need to create a new chain image file in `images/provider/chain.png` and specify the chain image URL like this  "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/provider/chain.png",

**Comment by chalabi2** [comment]
@HeesungB Thank you for the help!

**Comment by HeesungB** [comment]
@chalabi2 Could you remove the `coingecko` field?
I think it would be confusing for users to see the price of the testnet token.

**Comment by HeesungB** [comment]
@chalabi2 Thank you for contribution!

**Pull request merged**
