### PR TITLE
feat(Injective): add talis denom metadata

### PR DESCRIPTION
**Pull request by Canguilhem**

### CODE REVIEW

**Comment by HeesungB** [comment]
@Canguilhem Please add an image like the link example below.

{chiainIdentifier}/{factory token minimal denom}/{minimal denom}.png

https://github.com/chainapsis/keplr-chain-registry/tree/main/images/osmosis/factory/osmo14klwqgkmackvx2tqa0trtg69dmy0nrg4ntq4gjgw2za4734r5seqjqm4gm

**Comment by HeesungB** [comment]
@Canguilhem And Could you change image format to `png` from `webp`?

**Comment by Canguilhem** [comment]
sorry just saw the notification, will do

**Comment by HeesungB** [comment]
@Canguilhem Could you resize image to 256x256px?
```
Image size is not 256x256px. size : {"height":1209,"width":1209,"type":"png"}
```

**Comment by HeesungB** [comment]
@Canguilhem Please add an image like the link example below.

{chiainIdentifier}/{factory token minimal denom}/{minimal denom}.png

https://github.com/chainapsis/keplr-chain-registry/tree/main/images/osmosis/factory/osmo14klwqgkmackvx2tqa0trtg69dmy0nrg4ntq4gjgw2za4734r5seqjqm4gm

**Comment by HeesungB** [comment]
@Canguilhem Could you resolve conflict?

**Pull request merged**
