### PR TITLE
Add dydx and astro on Neutron

### PR DESCRIPTION
**Pull request by sotnikov-s**

### CODE REVIEW

**Comment by sotnikov-s** [comment]
I can see a CI error:

```
Do not provide ibc currency to currencies: ibc/5751B8BCDA688FD0A8EC0B292EEF1CDEAB4B766B63EC632778B196D317C40C3A
Error: Process completed with exit code 1.
```

but don't know what could be wrong tbh. where should I provide ibc currencies? could you please help?

**Comment by Thunnini** [comment]
In keplr, the IBC token is automatically fetched according to the path, so the IBC token should not be entered directly. In my opinion, if dydx comes from the cosmos-dydx mainnet, there is no need to enter it. In the case of ASTRO, you can put it in the currencies of the chain that is the original source of ASTRO.

**Comment by sotnikov-s** [comment]
> In keplr, the IBC token is automatically fetched according to the path, so the IBC token should not be entered directly. In my opinion, if dydx comes from the cosmos-dydx mainnet, there is no need to enter it. In the case of ASTRO, you can put it in the currencies of the chain that is the original source of ASTRO.

so, if to sum up, I need to remove dydx addition and move astro addition straight to phoenix.json currencies? thanks!

**Comment by Thunnini** [comment]
But what I'm curious about is ASTRO is cw20 or token factory?

**Comment by sotnikov-s** [comment]
> But what I'm curious about is ASTRO is cw20 or token factory?

in spite of the fact they have some customized tokenfactory module, their docs says that tokenfactory created denoms are of the same format as usually: factory/addr/subdenom https://docs.terra.money/develop/module-specifications/spec-token-factory so I believe it's a simple cw20, just as its denom implies:

```
neutrond q ibc-transfer denom-trace ibc/5751B8BCDA688FD0A8EC0B292EEF1CDEAB4B766B63EC632778B196D317C40C3A --node https://rpc-kralum.neutron-1.neutron.org:443 --chain-id neutron-1 --output json | jq .
{
  "denom_trace": {
    "path": "transfer/channel-5",
    "base_denom": "cw20:terra1nsuqsk6kh58ulczatwev87ttq2z6r3pusulg9r24mfj2fvtzd4uq3exn26"
  }
}
```

**Comment by Thunnini** [comment]
Hmm, does ASTRO token currently exist on terra and have you tried sending that token to neutron? I think it will be displayed in keplr without this PR...

**Comment by sotnikov-s** [comment]
> Hmm, does ASTRO token currently exist on terra and have you tried sending that token to neutron? I think it will be displayed in keplr without this PR...

hmm let me try!

**Comment by sotnikov-s** [comment]
yeah I can see them both, indeed, but astro has no logo

image

**Comment by Thunnini** [comment]
That's because keplr doesn't support that function regardless of keplr-chain-registry... We'll probably add feature to let cw20 token able to have image and coingecko id by January next year, but it's currently not possible.

**Comment by sotnikov-s** [comment]
ty for help! closing the PR then

**Pull request closed without merging**
