### PR TITLE
Add Mineplex Mainnet

### PR DESCRIPTION
**Pull request by mineplexio**

### CODE REVIEW

**Comment by HeesungB** [comment]
@mineplexio Hello Could you check your node?

```
Failed to connect websocket to /websocket rpc
```

**Comment by mineplexio** [comment]
> @mineplexio Hello Could you check your node?
> 
> ```
> Failed to connect websocket to /websocket rpc
> ```

Done, thanks

**Comment by HeesungB** [comment]
@mineplexio Is this chain using EVM? all token's decimal is 18.

**Comment by mineplexio** [comment]
> @mineplexio Is this chain using EVM? all token's decimal is 18.

Not yet, but it will soon

**Comment by HeesungB** [comment]
@mineplexio 
Should the user's account address be generated in the form of an Ethereum address?
If yes, you need to put the below feature

```
eth-address-gen: supports EVM account generation
eth-key-sign: supports EVM signatures
```

**Comment by mineplexio** [comment]
> @mineplexio Should the user's account address be generated in the form of an Ethereum address? If yes, you need to put the below feature
> 
> ```
> eth-address-gen: supports EVM account generation
> eth-key-sign: supports EVM signatures
> ```

No, they should not for now

**Comment by HeesungB** [comment]
@mineplexio Yes, please note that the account address may change in the future once the `eth-address-gen` feature is added.

**Pull request merged**
