### PR TITLE
Update highbury_710.json

### PR DESCRIPTION
**Pull request by sudopunk**
Add feature flags to support EVM addresses.

### CODE REVIEW

**Comment by sudopunk** [comment]
Yes

**Comment by HeesungB** [comment]
@sudopunk @Nimrostafarian Adding the `eth-address-gen` feature will change the account addressing system to ethereum, so it will not work for people who have been using cosmos addresses.

Is this a testnet or mainnet?

**Comment by HeesungB** [comment]
@Nimrostafarian So did this chain support ethereum from the beginning?

**Comment by HeesungB** [comment]
@Nimrostafarian Ok Thank you for contribution!

**Pull request merged**
