### PR TITLE
feat(network): Add gotabit testnet

### PR DESCRIPTION
**Pull request by jacksoom**
Add gotabit testnet

### CODE REVIEW

**Comment by jacksoom** [comment]
@HeesungB  pls help to review

**Comment by HeesungB** [comment]
@jacksoom Could you remove `coinGeckoId` field if it is `unknown`?

**Comment by jacksoom** [comment]
> 

fixed. thks

**Comment by jacksoom** [comment]
> @jacksoom Could you remove `coinGeckoId` field if it is `unknown`? And your chainIdentifer is `gotabit_testnet`, so Could you change json file name to `gotabit_testnet.json`?
fixed. pls review again

**Comment by jacksoom** [comment]
> @jacksoom Could you remove `coinGeckoId` field if it is `unknown`? And your chainIdentifer is `gotabit_testnet`, so Could you change json file name to `gotabit_testnet.json`?

fixed. pls review again

**Comment by HeesungB** [comment]
@jacksoom 
No.. You can't see NFTS on the kepIr web dashboard.
Could you change json file name to gotabit_testnet.json?

**Comment by jacksoom** [comment]
> 

file name seems is correct

**Comment by jacksoom** [comment]
> @jacksoom No.. You can't see NFTS on the kepIr web dashboard. Could you change json file name to gotabit_testnet.json?

gotabit_testnet.json that's it

**Comment by HeesungB** [comment]
@jacksoom Chain id is correct.
but, There is no coinGeckoId. so Could you remove `coinGeckoId`field in all currencies?
because I don't think the test net token should be priced and it's not listed on the coingecko site.

**Comment by jacksoom** [comment]
> coinGeckoId

done. thks for your comments

**Comment by HeesungB** [comment]
@jacksoom Thank you for contribution!

**Pull request merged**
