### PR TITLE
adds USDt for Kava chain

### PR DESCRIPTION
**Pull request by r0mille**
This update adds support for rendering USDt balances on Kava

cc: @downing034

### CODE REVIEW

**Comment by HeesungB** [comment]
@r0mille There is same PR in here. #217

**Comment by r0mille** [comment]
@HeesungB Thanks for pointing that out.

Rebased my branch and still want to make this update to correct "USDT" to "USDt" and to add an image and a coingeckoid.

Thanks!

**Comment by HeesungB** [comment]
@r0mille Can I'm wondering if "USDt" is correct.
I checked it here!
https://github.com/cosmos/chain-registry/blob/8c729d6954854fec21658a3c992d0d9b246966da/kava/assetlist.json#L107

**Comment by r0mille** [comment]
@HeesungB Yes it should be "USDt", we are simply following the media guidelines outlined by Tether https://tether.to/en/media/ 
Screenshot 2023-08-28 at 10 23 09 AM

I will also resolve the image resolution issue shortly.

**Comment by r0mille** [comment]
@HeesungB I uploaded the new image, checks have passed. I think we should be good to merge if you're ok with it. Thanks!

**Comment by HeesungB** [comment]
@r0mille Thank you for contribution!

**Pull request merged**
