### PR TITLE
Add Network: Terp Network

### PR DESCRIPTION
**Pull request by discoverdefiteam**

### CODE REVIEW

**Comment by HeesungB** [comment]
@discoverdefiteam 
```
Failed to connect websocket to /websocket rpc
```

Could you open Websocket or Change RPC URL?

**Comment by discoverdefiteam** [comment]
> @discoverdefiteam
> 
> ```
> Failed to connect websocket to /websocket rpc
> ```
> 
> Could you open Websocket or Change RPC URL?

Are there any resources you can reccommend that brings clarity to configuring an rpc node websocket?

**Comment by discoverdefiteam** [comment]
@HeesungB is it allowed to configure websocket as:
```
"rpc": "https://rpc-zenchainlabs.io",
"rest": "https://api-zenchainlabs.io",
"websocket": "wss://ws-terp.zenchainlabs.io"
```
?

**Comment by discoverdefiteam** [comment]
@HeesungB fixed.

**Comment by HeesungB** [comment]
@discoverdefiteam 
I can't find my CoinGecko ID `terp`.
Could you add it after registering on the CoinGecko website?

**Comment by discoverdefiteam** [comment]
yes will change to `unknown`

**Comment by HeesungB** [comment]
@discoverdefiteam Could you remove field?

**Comment by HeesungB** [comment]
@discoverdefiteam Thank you for contribution!

**Pull request merged**
