### PR TITLE
Add Levana Governance Token

### PR DESCRIPTION
**Pull request by lvn-rusty-dragon**

### CODE REVIEW

**Comment by Thunnini** [comment]
Please solve this.
```
Image size is not 256x256px. size : {"height":2000,"width":2000,"type":"png"}
```
Image size should be 256x256px and png.

**Comment by Thunnini** [comment]
The image position seems to be a little bit down. Is this okay?

**Comment by lvn-rusty-dragon** [comment]
Let me check with our graphics team.

**Comment by lvn-rusty-dragon** [comment]
Thanks for catching that, updated image now included.

**Pull request merged**
