### PR TITLE
Add Add cnho_stables

### PR DESCRIPTION
**Pull request by xiesh1982**

### CODE REVIEW

**Comment by editaahn** [comment]
Hi. Please check out the validation failure!
https://github.com/chainapsis/keplr-chain-registry/actions/runs/10033760169/job/27780428649?pr=723

**Comment by xiesh1982** [comment]
> Hi. Please check out the validation failure! https://github.com/chainapsis/keplr-chain-registry/actions/runs/10033760169/job/27780428649?pr=723

ok

**Comment by xiesh1982** [comment]
ok

**Comment by xiesh1982** [comment]
i had run the "yarn validate cosmos/cnhostables.json" at unbuntu and is fine. what is the problem on your environment or what is wrong on my configure.any advice

**Comment by editaahn** [comment]
Seems like an issue on our side. Sorry for the inconvenience. I'll check it and and get back to you

**Comment by editaahn** [comment]
Please pull the latest changes on main branch!

**Comment by xiesh1982** [comment]
ok

**Pull request closed without merging**
