### PR TITLE
added frog to columbus.js

### PR DESCRIPTION
**Pull request by Fidel2001**

### CODE REVIEW

**Comment by editaahn** [comment]
Hi. Were you supposed to register a CW token? 
If it's right, CW tokens are managed here.

https://github.com/chainapsis/keplr-contract-registry

**Comment by Fidel2001** [comment]
Frog is a cw20 on Columbus-5 but there is a IBC to Migaloo chain.. can you
double check it please

**Comment by Fidel2001** [comment]
can you verify it again please...

**Comment by editaahn** [comment]
Hi! The validation isn't able to accept registering CW token. CW token must be registered to the repository that I mentioned above. @Fidel2001

**Pull request closed without merging**
