### PR TITLE
Add DSR to Neutron Currencies

### PR DESCRIPTION
**Pull request by dinosaurgamelol**

### CODE REVIEW

**Comment by dinosaurgamelol** [comment]
Update DSR @HeesungB

**Comment by HeesungB** [comment]
@dinosaurgamelol Could you resolve conflict?

**Comment by dinosaurgamelol** [comment]
Check @HeesungB

**Comment by HeesungB** [comment]
@dinosaurgamelol Could you resolve conflict?

**Comment by dinosaurgamelol** [comment]
Check @HeesungB

**Pull request merged**
