### PR TITLE
Update rest api for nois

### PR DESCRIPTION
**Pull request by kaisbaccour**

### CODE REVIEW

**Comment by HeesungB** [comment]
@kaisbaccour Could you check below error?
and Is there reason to change rest endpoint?

```
SimpleFetchError: Failed to get response from https://nois-rpc.nysa.network/status
    at /home/runner/work/keplr-chain-registry/keplr-chain-registry/node_modules/@keplr-wallet/simple-fetch/src/fetch.ts:[9](https://github.com/chainapsis/keplr-chain-registry/actions/runs/6624014225/job/17992147844?pr=265#step:7:10)6:11
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/keplr-chain-registry/keplr-chain-registry/node_modules/@keplr-wallet/simple-fetch/build/fetch.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  baseURL: 'https://nois-rpc.nysa.network/',
  url: '/status',
  response: {
    url: 'https://nois-rpc.nysa.network/status',
    data: '404 page not found\n',
    headers: _HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    },
    status: 404,
    statusText: 'Not Found'
  }
}
```

**Comment by kaisbaccour** [comment]
> @kaisbaccour Could you check below error? and Is there reason to change rest endpoint?
> 
> ```
> SimpleFetchError: Failed to get response from https://nois-rpc.nysa.network/status
>     at /home/runner/work/keplr-chain-registry/keplr-chain-registry/node_modules/@keplr-wallet/simple-fetch/src/fetch.ts:[9](https://github.com/chainapsis/keplr-chain-registry/actions/runs/6624014225/job/17992147844?pr=265#step:7:10)6:11
>     at Generator.next (<anonymous>)
>     at fulfilled (/home/runner/work/keplr-chain-registry/keplr-chain-registry/node_modules/@keplr-wallet/simple-fetch/build/fetch.js:5:58)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5) {
>   baseURL: 'https://nois-rpc.nysa.network/',
>   url: '/status',
>   response: {
>     url: 'https://nois-rpc.nysa.network/status',
>     data: '404 page not found\n',
>     headers: _HeadersList {
>       cookies: null,
>       [Symbol(headers map)]: [Map],
>       [Symbol(headers map sorted)]: null
>     },
>     status: 404,
>     statusText: 'Not Found'
>   }
> }
> ```

The current rest API is down and we are not able to reach the validator this is why we want to change it to a more reliable one.

**Comment by kaisbaccour** [comment]
> https://nois-rpc.nysa.network/status

@HeesungB the error is fixed

**Comment by HeesungB** [comment]
@kaisbaccour Thank you for contribution!

**Pull request merged**
