### PR TITLE
Add Landslide Testnet to Keplr chain registry

### PR DESCRIPTION
**Pull request by riontric**

### CODE REVIEW

**Comment by editaahn** [comment]
Hi, please verify that all parts of the chain information are valid. The endpoints are invalid, and I'm unsure if the other values are actually usable, even if it's for a testnet chain.

**Comment by ramilexe** [comment]
Hi @editaahn thank you for your response 
What endpoints you checked and how?
Thank you

**Comment by editaahn** [comment]
The Github Action validation of this PR failed. https://github.com/chainapsis/keplr-chain-registry/actions/runs/10776710178/job/29966468187?pr=800

You can validate/test this code on your local environment. For the details, check the README please.

**Comment by editaahn** [comment]
Hi, I'm closing this PR for now. Please feel free to submit a new request if needed.

**Pull request closed without merging**
