### PR TITLE
Add fxcore network

### PR DESCRIPTION
**Pull request by zakir-code**

### CODE REVIEW

**Comment by HeesungB** [comment]
@zakir-code Hello.
Could you resize `chain.png` image to 256x256px?
And Your token image have to change file format to `png` and size to 256x256px.

**Comment by zakir-code** [comment]
@HeesungB Hi

Can you please review again?

**Comment by HeesungB** [comment]
@zakir-code Hi
Could you check your endpoint?
```
Failed to get response /status from rpc endpoint.
SimpleFetchError: Failed to get response from https://cosrpc.icplaza.pro/status
```

**Comment by zakir-code** [comment]
@HeesungB Hi

**Comment by HeesungB** [comment]
@zakir-code Thank you for contribution!

**Pull request merged**
