### PR TITLE
Add NINPO

### PR DESCRIPTION
**Pull request by iwillbuy**

### CODE REVIEW

**Comment by HeesungB** [comment]
@iwillbuy Hello. Is it factory token?

**Comment by iwillbuy** [comment]
@HeesungB Hello. CW20

**Comment by HeesungB** [comment]
@iwillbuy Could you add on below link?

https://github.com/chainapsis/keplr-contract-registry

**Comment by iwillbuy** [comment]
Check @HeesungB https://github.com/chainapsis/keplr-contract-registry/pull/18

**Comment by HeesungB** [comment]
@iwillbuy It merged. Thank you for contribution!

**Pull request closed without merging**
