### PR TITLE
Add POPEYE

### PR DESCRIPTION
**Pull request by popeyetheseilor**
Astroport token listing: https://github.com/astroport-fi/astroport-token-lists/pull/171

### CODE REVIEW

**Comment by HeesungB** [comment]
@popeyetheseilor Please add an image like the link example below.

`{chiainIdentifier}/{factory token minimal denom}/{minimal denom}.png`

https://github.com/chainapsis/keplr-chain-registry/tree/main/images/osmosis/factory/osmo14klwqgkmackvx2tqa0trtg69dmy0nrg4ntq4gjgw2za4734r5seqjqm4gm

**Comment by HeesungB** [comment]
@popeyetheseilor Could you resize image to 256x256px?

**Comment by popeyetheseilor** [comment]
@HeesungB Done.

**Comment by HeesungB** [comment]
@popeyetheseilor Your image size is `250x250px`, Could you resize to `256x256px`?

**Comment by afsardo** [comment]
@HeesungB Sorry, misread the dimensions, updated.

**Comment by popeyetheseilor** [comment]
@HeesungB  Sorry misread the dimensions, updated.

**Pull request merged**
