### PR TITLE
Changed Chain Medas Digital to Medas Digital 2.0

### PR DESCRIPTION
**Pull request by oxygene76**
Due to Hardfork we updated chain id to medasdigital-2

### CODE REVIEW

**Comment by delivan** [comment]
@oxygene76 RPC endpoint in the chain info seems doesn't work. Could you check it out?
Screenshot 2024-11-14 at 4 16 07 PM

**Comment by oxygene76** [comment]
Hi, May we rerun the check? I changed the certificate thereafter.

**Comment by oxygene76** [comment]
image

**Review by oxygene76 — COMMENTED** [review]
just Rerun checks

**Review by oxygene76 — COMMENTED** [review]
Rerun Validation check

**Review by oxygene76 — COMMENTED** [review]
Rerun Check

**Pull request merged**
