### PR TITLE
feat: add kakarot starknet sepolia

### PR DESCRIPTION
**Pull request by swetshaw**
Add support for Kakarot Starknet Sepolia

### CODE REVIEW

**Review by editaahn — COMMENTED** [review]
Hi. Please add information of `nodeProvider` and update the image size to 256*256px.
Also, the name shouldn't exceed 30 letters.

**Comment by swetshaw** [comment]
Hi @editaahn , pushed new commits based on your suggestions, can you review again?

**Comment by editaahn** [comment]
Would you mind pulling current changes of the repo?

**Comment by swetshaw** [comment]
no problem, pulling the latest changes

**Pull request merged**
