### PR TITLE
 old website stoped ,  commit new rpc

### PR DESCRIPTION
**Pull request by newblockgen**
old rpc stoped ,  commit new rpc

### CODE REVIEW

**Review by newblockgen — COMMENTED** [review]
deprecated old chain ,commit new chain

**Comment by newblockgen** [comment]
check error is  " Invalid image url: https://raw.githubusercontent.com/neutron-org/chain-registry/master/testnets/seitestnet/images/sei.png " ,  this file is not mine.

**Review by newblockgen — COMMENTED** [review]
commit again

**Comment by HeesungB** [comment]
@newblockgen Thank you for contribution!

**Pull request merged**
