### PR TITLE
Remove pulsar.json

### PR DESCRIPTION
**Pull request by luca992**
The presence of pulsar breaks a the ability to suggest pulsar-3 if (pulsar-2 is defined here). Or the ability to suggest pulsar-2 (if pulsar-3 is defined here). Until pulsar-2 is taken down I don't think pulsar-2 or pulsar-3 should be defined here... unless a proper fix in keplr was implemented to make sure the chain ids actually match from the community repo to what the user supplied, and if not use what the person actually suggested.

https://github.com/chainapsis/keplr-wallet/blob/8ab00c015c12a274f7570f0aca7bb7c656f85230/packages/stores/src/core/interaction/chain-suggest.ts#L66

### CODE REVIEW

**Comment by HeesungB** [comment]
@luca992 How about keep the current file and change to pulse-3 later?

**Comment by luca992** [comment]
> @luca992 How about keep the current file and change to `pulse-3` later?

As I was trying to say people cannot suggest the `pulsar-3` network in keplr while the `pulsar.json` file exists here because it will overwrite their suggestion with the config here.

**Comment by HeesungB** [comment]
@luca992 I got it!
Should I leave the image?

**Comment by luca992** [comment]
I would leave them if it were up to me. That way people can use them in their suggested configs. Also, once `pulsar-2` is taken off line `pulsar.json` could be added back in without causing anyone issues.

**Pull request merged**
