### PR TITLE
Add Self Chain (SLF)

### PR DESCRIPTION
**Pull request by philiparthurmoore**

### CODE REVIEW

**Comment by editaahn** [comment]
Hi!
- The image file/directory names have to follow the chain identifier. (You can find the details on its README)
- Please make sure coinGeckoId is available in CoinGecko website.

**Comment by philiparthurmoore** [comment]
Hi @editaahn - we have made the necessary modifications. Please check. Thank you!

**Comment by editaahn** [comment]
Since Keplr needs coinGeckoId for fetching prices and Coin Gecko right now seems it doesn't manage Self Chain token price, would you mind registering other information only, except for coinGeckoId?

**Comment by philiparthurmoore** [comment]
> Since Keplr needs coinGeckoId for fetching prices and Coin Gecko right now seems it doesn't manage Self Chain token price, would you mind registering other information only, except for coinGeckoId?

Absolutely @editaahn - we've removed the `coinGeckoId` stuff for now. We're [migrating from FRONT to SLF](https://blog.selfchain.xyz/front-to-slf-migration-details/) so once that price feed becomes available we can add it into Keplr JSON. For now everything else looks good to merge, I hope. 

Let me know - thanks so much.

**Comment by editaahn** [comment]
Thank you! Additonally, the JSON name and image directory name should be `self`.

**Comment by philiparthurmoore** [comment]
> Thank you! Additonally, the JSON name and image directory name should be `self`.

Done. 👍🏽

**Pull request merged**
