### PR TITLE
Add iconLake testnet

### PR DESCRIPTION
**Pull request by huanxiangspace**

### CODE REVIEW

**Comment by HeesungB** [comment]
@huanxiangspace We didn't support svg file at image. Could you convert to png from svg?

**Comment by huanxiangspace** [comment]
@HeesungB OK, no problem. But I have a question, why didn't support svg which has so many Advantages.

**Comment by huanxiangspace** [comment]
> @huanxiangspace We didn't support svg file at image. Could you convert to png from svg?

**Comment by HeesungB** [comment]
@huanxiangspace Support for SVG files is coming soon!

**Comment by HeesungB** [comment]
@huanxiangspace Your chain identifier is `iconlake-testnet`, so Could you rename to `images/iconlake-testnet` from `images/iconlake`?

and you have to change `chainSymbolImageUrl` and `coinImageUrl` fields.

**Comment by huanxiangspace** [comment]
> @huanxiangspace Your chain identifier is `iconlake-testnet`, so Could you rename to `images/iconlake-testnet` from `images/iconlake`?
> 
> and you have to change `chainSymbolImageUrl` and `coinImageUrl` fields.

@HeesungB It's done.

**Comment by HeesungB** [comment]
@huanxiangspace Image size should be 256x256px size.

It would be helpful to read this [link](https://github.com/chainapsis/keplr-chain-registry#requirement-details).

and You can test on local using below command.
```
yarn install
yarn validate cosmos/iconlake-testnet.json
```

**Comment by huanxiangspace** [comment]
@HeesungB Sorry, I forgot to validate. All checked. Thank for your time.

**Comment by HeesungB** [comment]
@huanxiangspace Could you rename the token image file to the `coinMinimalDenom`?
and You should to change `coinImageUrl ` value!

**Comment by huanxiangspace** [comment]
@HeesungB The imgs have been renamed.

**Comment by HeesungB** [comment]
@huanxiangspace Thank you for contribution!

**Pull request merged**
