### PR TITLE
Add persistence test-core-2 chain

### PR DESCRIPTION
**Pull request by saurabhfegade**

### CODE REVIEW

**Comment by HeesungB** [comment]
@saurabhfegade Hello.
Could you check your chain identifier?
```
Chain identifier unmatched: (expected: test-core-2, actual: test-core)
```

**Comment by saurabhfegade** [comment]
> @saurabhfegade Hello. Could you check your chain identifier?
> 
> ```
> Chain identifier unmatched: (expected: test-core-2, actual: test-core)
> ```

hey @HeesungB, the chain identifier is test-core-2 itself, can you please tell where it's taking the "test-core" from?

**Comment by saurabhfegade** [comment]
Hi @HeesungB, fixed the issues, can you please check again?

**Comment by HeesungB** [comment]
@saurabhfegade Thank you for contribution!

**Pull request merged**
