### PR TITLE
fix canto config

### PR DESCRIPTION
**Pull request by blacklodge-admin**
This is the merged superset of the existing config and the only config I was able to find that allowed me to transact reliably (via nodestake!).  The main bits are...
- fee configuration via`gasPriceStep`
- use the cosmos.directory API proxies rather than pinning to one operator's
- enable IBC feature flags

### CODE REVIEW

**Review by wegfox — APPROVED** [review]

**Comment by wegfox** [comment]
using the command to verify the file (yarn validate cosmos/canto_7700.json) finds errors.
I believe the config order is out of standard, according to the error I received here: "Only non recognizable feature should be provided: ibc-transfer" ,maybe not need this flags too,  I was only able to pass the verification without errors with this file here:

{
  "rpc": "https://rpc.canto.nodestake.top/", 
  "rest": "https://mainnode.plexnode.org:1317",
  "chainId": "canto_7700-1",
  "chainName": "Canto",
  "chainSymbolImageUrl": "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/canto_7700/chain.png",
  "nodeProvider": {
    "name": "Plex Labs",
    "email": "contact@plex.engineer",
    "website":"https://plex.engineer/"
  },
  "stakeCurrency": {
    "coinDenom": "CANTO",
    "coinMinimalDenom": "acanto",
    "coinDecimals": 18,
    "coinGeckoId": "canto"
  },
  "walletUrl": "https://canto.io/",
  "walletUrlForStaking": "https://canto.io/staking",
  "bip44": {
    "coinType": 60
  },
  "bech32Config": {
    "bech32PrefixAccAddr": "canto",
    "bech32PrefixAccPub": "cantopub",
    "bech32PrefixValAddr": "cantovaloper",
    "bech32PrefixValPub": "cantovaloperpub",
    "bech32PrefixConsAddr": "cantovalcons",
    "bech32PrefixConsPub": "cantovalconspub"
  },
  "currencies": [
    {
      "coinDenom": "CANTO",
      "coinMinimalDenom": "acanto",
      "coinDecimals": 18,
      "coinGeckoId": "canto"
    }
  ],
  "feeCurrencies": [
    {
      "coinDenom": "CANTO",
      "coinMinimalDenom": "acanto",
      "coinDecimals": 18,
      "coinGeckoId": "canto",
      "gasPriceStep": {
                "low": 500000000000,
                "average": 1000000000000,
                "high": 4000000000000
            }
    }
  ],
  "features": [
    "eth-address-gen",
    "eth-key-sign"
  ]
}

**Review by wegfox — CHANGES_REQUESTED** [review]
using the command to verify the file (yarn validate cosmos/canto_7700.json) finds errors.
I believe the config order is out of standard, according to the error I received here: "Only non recognizable feature should be provided: ibc-transfer" ,maybe not need this flags too, I was only able to pass the verification without errors with this file here:

{
  "rpc": "https://rpc.canto.nodestake.top/", 
  "rest": "https://mainnode.plexnode.org:1317",
  "chainId": "canto_7700-1",
  "chainName": "Canto",
  "chainSymbolImageUrl": "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/canto_7700/chain.png",
  "nodeProvider": {
    "name": "Plex Labs",
    "email": "contact@plex.engineer",
    "website":"https://plex.engineer/"
  },
  "stakeCurrency": {
    "coinDenom": "CANTO",
    "coinMinimalDenom": "acanto",
    "coinDecimals": 18,
    "coinGeckoId": "canto"
  },
  "walletUrl": "https://canto.io/",
  "walletUrlForStaking": "https://canto.io/staking",
  "bip44": {
    "coinType": 60
  },
  "bech32Config": {
    "bech32PrefixAccAddr": "canto",
    "bech32PrefixAccPub": "cantopub",
    "bech32PrefixValAddr": "cantovaloper",
    "bech32PrefixValPub": "cantovaloperpub",
    "bech32PrefixConsAddr": "cantovalcons",
    "bech32PrefixConsPub": "cantovalconspub"
  },
  "currencies": [
    {
      "coinDenom": "CANTO",
      "coinMinimalDenom": "acanto",
      "coinDecimals": 18,
      "coinGeckoId": "canto"
    }
  ],
  "feeCurrencies": [
    {
      "coinDenom": "CANTO",
      "coinMinimalDenom": "acanto",
      "coinDecimals": 18,
      "coinGeckoId": "canto",
      "gasPriceStep": {
                "low": 500000000000,
                "average": 1000000000000,
                "high": 4000000000000
            }
    }
  ],
  "features": [
    "eth-address-gen",
    "eth-key-sign"
  ]
}

**Comment by blacklodge-admin** [comment]
> using the command to verify the file (yarn validate cosmos/canto_7700.json) finds errors. I believe the config order is out of standard, according to the error I received here: "Only non recognizable feature should be provided: ibc-transfer" ,maybe not need this flags too, I was only able to pass the verification without errors with this file here:
> 
> { "rpc": "https://rpc.canto.nodestake.top/", "rest": "https://mainnode.plexnode.org:1317", "chainId": "canto_7700-1", "chainName": "Canto", "chainSymbolImageUrl": "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/canto_7700/chain.png", "nodeProvider": { "name": "Plex Labs", "email": "[contact@plex.engineer](mailto:contact@plex.engineer)", "website":"https://plex.engineer/" }, "stakeCurrency": { "coinDenom": "CANTO", "coinMinimalDenom": "acanto", "coinDecimals": 18, "coinGeckoId": "canto" }, "walletUrl": "https://canto.io/", "walletUrlForStaking": "https://canto.io/staking", "bip44": { "coinType": 60 }, "bech32Config": { "bech32PrefixAccAddr": "canto", "bech32PrefixAccPub": "cantopub", "bech32PrefixValAddr": "cantovaloper", "bech32PrefixValPub": "cantovaloperpub", "bech32PrefixConsAddr": "cantovalcons", "bech32PrefixConsPub": "cantovalconspub" }, "currencies": [ { "coinDenom": "CANTO", "coinMinimalDenom": "acanto", "coinDecimals": 18, "coinGeckoId": "canto" } ], "feeCurrencies": [ { "coinDenom": "CANTO", "coinMinimalDenom": "acanto", "coinDecimals": 18, "coinGeckoId": "canto", "gasPriceStep": { "low": 500000000000, "average": 1000000000000, "high": 4000000000000 } } ], "features": [ "eth-address-gen", "eth-key-sign" ] }

Ah, I had no idea that order somehow mattered and had just told `jq` to sort all the object fields when merging the two config files :(

I'll unwind that sorting and hack at it locally until keplr can transact successfully and the aforementioned yarn target is quiet.  Sorry for all the back and forth here.

**Comment by HeesungB** [comment]
Hello @dsudit01
There's something that needs to be changed

1. Could you remove ibc-go, ibc-transfer in features.
2. `gasPriceStep` should be within currency field.
3. I failed to get response /status from rpc endpoint. -> Could you check it?

You can check using `yarn validate cosmos/canto_7700.json` command

**Comment by HeesungB** [comment]
@blacklodge-admin @wegfox I'm closing the PR because it's been sitting for too long, but if you need it, please open it or raise it again.

**Pull request closed without merging**
