### PR TITLE
Add dHealth Testnet Chain

### PR DESCRIPTION
**Pull request by nsonanh**

### CODE REVIEW

**Comment by HeesungB** [comment]
@nsonanh Hello.
Could you check your node?
```
Failed to connect websocket to /websocket rpc
```

**Comment by nsonanh** [comment]
> @nsonanh Hello. Could you check your node?
> 
> ```
> Failed to connect websocket to /websocket rpc
> ```

@HeesungB Hi,
It should be ok now, I tried connecting with Leap wallet nodes are running fine.
Can we rerun the checks ?

**Comment by nsonanh** [comment]
> @nsonanh Hello. Could you check your node?
> 
> ```
> Failed to connect websocket to /websocket rpc
> ```

It's working now, can we run the checks again ?

**Comment by HeesungB** [comment]
@nsonanh Websocket is working.
but Could you rename your chain image url hostname?
from `https://raw.githubusercontent.com/dhealthproject`
to `https://raw.githubusercontent.com/chainapsis`

```
https://raw.githubusercontent.com/dhealthproject/keplr-chain-registry/main/images/dhealth-testnet/chain.png
```

**Comment by nsonanh** [comment]
Image url hostname updated, ptal

**Pull request merged**
