### PR TITLE
Add Wind token to Juno token repository - add tokenfactory path to token image

### PR DESCRIPTION
**Pull request by poonc**

### CODE REVIEW

**Comment by HeesungB** [comment]
@poonc Hello. Do you want to use this token as `fee currency`?

**Comment by poonc** [comment]
Sure would be nice to do so...Am 24.03.24, 01:54 schrieb HeesungB ***@***.***>:

   
  @poonc Hello. Do you want to use this token as fee currency?

**Comment by HeesungB** [comment]
@poonc It must first be added to currencies in order to be added to fee currencies.
And before a `Factory Token` can be used as a Fee, it must be accepted by the chain.

**Comment by poonc** [comment]
Probably it would be best to leave it for now- only on whitewhale dex, price feed not on osmosis yet...--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 27.03.24, 06:02 schrieb HeesungB ***@***.***>:

   
  @poonc It must first be added to currencies in order to be added to fee currencies. And before a Factory Token can be used as a Fee, it must be accepted by the chain.

**Comment by editaahn** [comment]
Hi, I'm closing this PR for now. Please feel free to submit a new request if needed.

**Pull request closed without merging**
