### PR TITLE
update composable name and prefix

### PR DESCRIPTION
**Pull request by JafarAz**
This PR introduces three core changes:

1. Update `Composable` chain name to `Picasso`
2. Update `centauri` prefix to `pica`
3. Addition of assets that are being bridged from Ethereum via Picasso

If all passes checked, Please do not merge this PR until Wednesday as that is when the chain will be upgraded and the prefix will be changed.

### CODE REVIEW

**Comment by editaahn** [comment]
Hi. Please make sure the image sizes are 256*256px.

**Comment by JafarAz** [comment]
yeah apologies, took a while but updated sizes @editaahn

**Comment by JafarAz** [comment]
Would it be possible to merge this around 17:00 UTC? That is when the chain upgrade takes place

**Comment by editaahn** [comment]
Would it be okay to merge it at 15:00 UTC? 17:00 UTC is 2:00 KST, too early for Keplr dev team's timezone.

**Comment by editaahn** [comment]
We've concluded that it's better to merge it after the chain upgrade and testing it on Keplr, due to its prefix change. Would it be fine if I approve the merge 8-10 hours later than the upgrade?

**Comment by JafarAz** [comment]
@editaahn 15:00 UTC works, we've tested this change on testnet in my previous PR and it worked smoothly afterwards.

**Comment by JafarAz** [comment]
I've sent you the PICA, the chain upgrade will occur in under an hour. Would really appreciate if you could merge the PR as it will then mean that Keplr will be unusable for users for 8 hours

**Comment by editaahn** [comment]
Sorry for making you wait due to the timezone issue. The PR was merged, and the test was done.

**Comment by JafarAz** [comment]
No worries @editaahn 

Appreciate it

One question, what is the best solution to providing an RPC to the registry? the current one from lavender seems to be hitting the rate limit often

**Pull request merged**
