### PR TITLE
ethWETH on pacific-1 has 8 decimals of precision

### PR DESCRIPTION
**Pull request by lvn-rusty-dragon**

### CODE REVIEW

**Comment by HeesungB** [comment]
@lvn-rusty-dragon How can I check infromation about factory token?

**Comment by lvn-rusty-dragon** [comment]
I'm not sure who would be the right authority on this, all I know is that the wallet I have contains 1 ETH and it displays in the Keplr UI as 100. All the other ETH entries have 8 decimals set. I can ping some people on Telegram who would be more authoritative to weigh in.

**Comment by lvn-rusty-dragon** [comment]
Also, pinging @besated who added pacific.json.

**Comment by HeesungB** [comment]
@lvn-rusty-dragon OK! I merged it!

**Comment by lvn-rusty-dragon** [comment]
Awesome, thank you! And I can confirm that I no longer have 100 ETH in Keplr, just the 1 I should have.

**Comment by HeesungB** [comment]
@lvn-rusty-dragon Thank you for contribution!

**Pull request merged**
