### PR TITLE
Add support for CRBRUS on Osmosis

### PR DESCRIPTION
**Pull request by monet-supply**
The Cerberus chain was shut down earlier this year based on community vote (see: https://medium.com/@windpowerstake/closing-cerberus-c74df872d669). The CRBRUS tokens that were IBC transferred to Osmosis before closure are the only tradable tokens, and CRBRUS is effectively now an Osmosis native token. This PR updates info to add support to Osmosis-native CRBRUS in Keplr wallet.

### CODE REVIEW

**Comment by HeesungB** [comment]
@monet-supply Please add an image like the link example below.

{chiainIdentifier}/{factory token minimal denom}/{minimal denom}.png

https://github.com/chainapsis/keplr-chain-registry/tree/main/images/osmosis/factory/osmo14klwqgkmackvx2tqa0trtg69dmy0nrg4ntq4gjgw2za4734r5seqjqm4gm

**Comment by monet-supply** [comment]
@HeesungB name/location should be fixed now! I named the token denom folder as ibc-41999DF04D9441DAC0DF5D8291DF4333FBCBA810FFD63FDCE34FDF41EF37B6F7 (instead of ibc/41999DF04D9441DAC0DF5D8291DF4333FBCBA810FFD63FDCE34FDF41EF37B6F7) to avoid creating another level in file directory. Let me know if there's any other issues. Thanks

**Comment by HeesungB** [comment]
@monet-supply Oh My bad.
IBC token can't add in currencies.
If you add both chain(OSMOSIS, CERBERUS), You can see ibc token on Keplr.

**Comment by monet-supply** [comment]
For some reason haven't been able to see CRBRUS in Keplr extension (although it does look like it is visible in the website app). Web app support is good, but would love to have support on extension/mobile as well because some chains (eg Kujira) aren't listed in the web app. I've had to use Leap wallet for certain stuff as a workaround as it is visible there.

**Comment by HeesungB** [comment]
@monet-supply Yes, we are aware of the issue.
It's hard to show it in the current structure, so I'll see what I can do.

**Pull request closed without merging**
