### PR TITLE
Add Provenance chain

### PR DESCRIPTION
**Pull request by webbushka**

### CODE REVIEW

**Comment by webbushka** [comment]
Quick question: Does it make sense to add testnets to the registry as well?

**Comment by arnabghose997** [comment]
@webbushka  I have a same question as well. 

I also have another query. If the REST and RPC endpoints, provided by the Project's Team, are changed maybe like 2-3 months after the PR have been merged, will a new PR to incorporate the endpoints change will be considered?

**Comment by HeesungB** [comment]
@webbushka 
Yes. It is ok.
Do you want to merge?

@arnabghose997 
It is possible to update the RPC/REST URL with PR that updates the chain information.
But I don't know exactly what will happen in 2-3 months.

**Comment by arnabghose997** [comment]
@HeesungB  Thanks for reply. Actually, our testnet is live since 28th September 2022 and we have registered our chain in the Cosmos Registry as well. The reason to ask that question was because our team has planned to move to a different cloud server, to host the Foundation Node, and also have decided to rename our RPC and REST endpoints. So, we thought to raise PR here after our Validator Node migration is complete

**Comment by webbushka** [comment]
@HeesungB I will add a file for our testnet, it will use the same image, do you want me to add another image folder or can I reuse that image in the testnet file?

**Comment by HeesungB** [comment]
@arnabghose997 
I understand about that!
It is ok that you regist first and change after.

**Comment by HeesungB** [comment]
@webbushka 
It's okay to use same image, but you have to make directory about test net(ex. `images/pio-testnest/chain.png`)

**Comment by HeesungB** [comment]
@webbushka 
Thank you for contribution!👍

**Comment by webbushka** [comment]
@HeesungB ok pushed that change, I'm ready for merge if you are good 👍🏼

**Pull request merged**
