### PR TITLE
Add Evmos Testnet - evmos_9000-4.json

### PR DESCRIPTION
**Pull request by qubelabsio**

### CODE REVIEW

**Comment by HeesungB** [comment]
@qubelabsio Hello.
Could you check your chain identifer?
```
Chain identifier unmatched: (expected: evmos_9000, actual: evmos_9000-4)
```

**Comment by qubelabsio** [comment]
> @qubelabsio Hello. Could you check your chain identifier?
> 
> ```
> Chain identifier unmatched: (expected: evmos_9000, actual: evmos_9000-4)
> ```

Chain id should be `evmos_9000-4`, according to https://docs.evmos.org/validate/testnet#pick-a-testnet.

**Comment by HeesungB** [comment]
@qubelabsio The chain json file should be named `{chain identifier}.json`.
In the link below, the `chain id` is split into `chain identifier` and `version`.
https://github.com/chainapsis/keplr-chain-registry?tab=readme-ov-file#requirement-details

**Comment by qubelabsio** [comment]
> @qubelabsio The chain json file should be named `{chain identifier}.json`. In the link below, the `chain id` is split into `chain identifier` and `version`. https://github.com/chainapsis/keplr-chain-registry?tab=readme-ov-file#requirement-details

Thank you! I have modified the filename now.

**Comment by HeesungB** [comment]
@qubelabsio Could you check your node?
```
Failed to connect websocket to /websocket rpc
```

**Comment by editaahn** [comment]
Hi, I'm closing this PR for now. Please feel free to submit a new request if needed.

**Pull request closed without merging**
