### PR TITLE
Cifer Chain Registration

### PR DESCRIPTION
**Pull request by cifer-ai**
$CIF tokens are live on the Cifer Mainnet and can be sent and received via our website, block.cifer.ai. We are actively developing the platform and plan to utilize $CIF in multiple ways as real-use cases:

Gas Fee and Transaction Fee: $CIF will serve as the primary currency for paying gas fees and transaction fees on the Cifer blockchain. This will incentivize users to hold and utilize $CIF within the ecosystem.

AI Model Training Incentives: Users who provide data or computational resources for training AI models on the CiferAI platform will be rewarded with $CIF tokens. This incentivizes participation and ensures a robust and decentralized training process.

Governance and Voting: In the future, $CIF holders will have voting rights on key decisions and proposals related to the CiferAI protocol and development roadmap. This grants token holders control and fosters community engagement.

### CODE REVIEW

**Comment by HeesungB** [comment]
@cifer-ai Hello.
Can you edit the file using the link below?
https://github.com/chainapsis/keplr-chain-registry#requirement-details

You can also use the command below to check the validation locally.
```
yarn validate cosmos/cifer.json
```

**Comment by cifer-ai** [comment]
Hi, thank you for preview.
We have update CoinGecko ID in cifer.json file.

**Comment by cifer-ai** [comment]
We have updated the RPC and REST URLs to align with those used by other chains, resulting in a consistent API list across different blockchains.

**Comment by HeesungB** [comment]
@cifer-ai Could you check your node? Websocket is not working
```
Failed to connect websocket to /websocket rpc
```

**Pull request closed without merging**
