### PR TITLE
Create arctic-1 (devnet)

### PR DESCRIPTION
**Pull request by codebycarson**
Added the Sei devnet called arctic-1

### CODE REVIEW

**Comment by codebycarson** [comment]
This is the official Sei devnet.

There are three chains for Sei pacific-1 (mainnet), atlantic-2 (testnet), and arctic-1 (devnet)

**Comment by HeesungB** [comment]
@codebycarson Could you check your file name?
It should be `.json` file.

**Comment by HeesungB** [comment]
@codebycarson Could you add node provider email?
```
"nodeProvider.email" is required
```

**Comment by codebycarson** [comment]
> @codebycarson Could you add node provider email?
> 
> ```
> "nodeProvider.email" is required
> ```

Fixed!

**Comment by HeesungB** [comment]
@codebycarson Thank you for contribution!

**Pull request merged**
