### PR TITLE
add hydro-protocol

### PR DESCRIPTION
**Pull request by hydro-developer**

### CODE REVIEW

**Comment by HeesungB** [comment]
@hydro-developer Is this factory token?

**Comment by hydro-developer** [comment]
> @hydro-developer Is this factory token? then Could you check `coinMinimalDenom` field? and You should move image file under directory under named by factory token's coinMinimalDenom
> 
> ```
> {
>       "coinDenom": "IBCX",
>       "coinMinimalDenom": "factory/osmo14klwqgkmackvx2tqa0trtg69dmy0nrg4ntq4gjgw2za4734r5seqjqm4gm/uibcx",
>       "coinDecimals": 6,
>       "coinImageUrl": "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/osmosis/factory/osmo14klwqgkmackvx2tqa0trtg69dmy0nrg4ntq4gjgw2za4734r5seqjqm4gm/uibcx.png"
>     },
> ```

hINJ is cw20 token contract.
https://explorer.injective.network/contract/inj18luqttqyckgpddndh8hvaq25d5nfwjc78m56lc/  

I updated image file name to {denom}.png

**Comment by HeesungB** [comment]
@hydro-developer Could you add on this repository?
https://github.com/chainapsis/keplr-contract-registry

**Comment by hydro-developer** [comment]
> @hydro-developer Could you add on this repository? https://github.com/chainapsis/keplr-contract-registry

Ok thanks. I will close this PR (here is new PR : https://github.com/chainapsis/keplr-contract-registry/pull/12)

**Pull request closed without merging**
