### PR TITLE
Add comdex network details

### PR DESCRIPTION
**Pull request by dheerajkd30**

### CODE REVIEW

**Comment by HeesungB** [comment]
@dheerajkd30
Thank you for contribution!
I don't know why github action is not working.

Chain logos should be in PNG format in 256x256px resolution.
You should change your image size.

**Comment by dheerajkd30** [comment]
> @dheerajkd30 Thank you for contribution! I don't know why github action is not working.
> 
> Chain logos should be in PNG format in 256x256px resolution. You should change your image size.

@HeesungB  I have updated the image resolution.

**Comment by HeesungB** [comment]
@dheerajkd30 

You should add node provider field.

```json
  "nodeProvider": {
    "name": "Blockapsis",
    "email": "infra@blockapsis.com",
    "website":"https://blockapsis.com/"
  },
```

**Comment by dheerajkd30** [comment]
> @dheerajkd30
> 
> You should add node provider field.
> 
> ```json
>   "nodeProvider": {
>     "name": "Blockapsis",
>     "email": "infra@blockapsis.com",
>     "website":"https://blockapsis.com/"
>   },
> ```

Done.

**Pull request merged**
