### PR TITLE
update endpoint for composable

### PR DESCRIPTION
**Pull request by hoangdv2429**
This PR will update Endpoints for Composable

### CODE REVIEW

**Comment by hoangdv2429** [comment]
Good morning sir @delivan . Can you have a look at this PR ? thank you!

**Comment by hoangdv2429** [comment]
@delivan I'm not sure why the PR validation test failed. Do I need to change anything ? thank you

**Comment by HeesungB** [comment]
@hoangdv2429 Could you check node websocket?
```
Failed to connect websocket to /websocket rpc
```

**Comment by hoangdv2429** [comment]
@HeesungB Thank you for checking this! Polkachu does not support websocket on their RPC (I suppose they're doing some internal stuff). I'll consult with the team and update another endpoint. Once again thank you very much!

**Comment by HeesungB** [comment]
@hoangdv2429 Yes, we need websocket support because Keplr has services that use websocket. Thank you

**Comment by hoangdv2429** [comment]
Nodestake is up again so I'll close this

**Comment by hoangdv2429** [comment]
because Nodestake endpoints is unstable, I reopen this PR with Notional endpoints.

**Comment by HeesungB** [comment]
@hoangdv2429 Thank you for contribution!

**Pull request merged**
