### PR TITLE
feat: add astro and xastro

### PR DESCRIPTION
**Pull request by afsardo**

### CODE REVIEW

**Comment by HeesungB** [comment]
@afsardo Hello. Is it factory token?

**Comment by afsardo** [comment]
It's a CW20 for now.

**Comment by HeesungB** [comment]
@afsardo Could you add on below link?

https://github.com/chainapsis/keplr-contract-registry

**Comment by afsardo** [comment]
@HeesungB Done.

https://github.com/chainapsis/keplr-contract-registry/pull/21

**Pull request closed without merging**
