### PR TITLE
Add Chain4Energy on keplr chain-registry

### PR DESCRIPTION
**Pull request by Panvasi**

### CODE REVIEW

**Comment by Panvasi** [comment]
Ready to merge.

**Review by Panvasi — COMMENTED** [review]
Ready to merge

**Review by editaahn — CHANGES_REQUESTED** [review]

**Comment by Panvasi** [comment]
@editaahn

**Comment by editaahn** [comment]
- coinGeckoIds in currencies/stakeCurrency/feeCurrencies should be removed. Please remove the line, instead of remaining the empty string("").
- Your chain identifier is `perun`(Ref. https://github.com/chainapsis/keplr-chain-registry?tab=readme-ov-file#chain-registration-directory-structure).

**Review by Panvasi — COMMENTED** [review]
Done

**Comment by editaahn** [comment]
- The name of JSON should be changed to perun.json as well.
- Directory names are case-sensitive. Use perun instead of Perun

**Comment by Panvasi** [comment]
> * The name of JSON should be changed to perun.json as well.
> * Directory names are case-sensitive. Use perun instead of Perun

Resolved

**Comment by Panvasi** [comment]
@editaahn Everything seems okay now

**Pull request merged**
