### PR TITLE
Add paloma

### PR DESCRIPTION
**Pull request by kinrokinro**
1. There is no coingecko ID right now, but probably it will be "paloma" I suppose
2. Chain-id check is also failed (project title and chain id is different), but submitted values correct (`"network": "messenger"`)

### CODE REVIEW

**Comment by HeesungB** [comment]
Hello @kinrokinro.
There's something that needs to be changed

1. If chain id is `paloma`, JSON file name should be `paloma.json` and File directory name should be too.
But If chain id is `messenger` JSON file name should be `messenger.json` and File directory name should be too.

2. Image size will be 256x256px.

**Comment by kinrokinro** [comment]
@HeesungB should be fixed now

**Comment by HeesungB** [comment]
@kinrokinro Thank you for contribution!

**Comment by taariq** [comment]
@kinrokinro just an FYI: We've updated Paloma to a new chain-id: `tumbler`. Will you update this merge with another PR?

**Comment by taariq** [comment]
@HeesungB we are updated with a new request here: https://github.com/chainapsis/keplr-chain-registry/pull/605

**Pull request merged**
