### PR TITLE
Add banksy testnet

### PR DESCRIPTION
**Pull request by JafarAz**
Added json file for Composable testnet. Please let me know if there are any issues with the current file; happy to rectify them.

### CODE REVIEW

**Comment by HeesungB** [comment]
@JafarAz The chain's image should be under the directory named identifier for that chain.

**Comment by JafarAz** [comment]
Edited sir @HeesungB

**Comment by HeesungB** [comment]
@JafarAz I think that your chain identifier is `banksy-testnet`.
So Could you rename image directory name to `banksy-testnet` from `banksy` and image urls.

**Comment by JafarAz** [comment]
Ty ser, updated @HeesungB

**Comment by HeesungB** [comment]
@JafarAz Can you check your node?
Here is error logs.
```
SimpleFetchError: Failed to get response from https://api-testnet5.composable-cosmos.composablenodes.tech/cosmos/base/tendermint/v1beta1/node_info
    at /home/runner/work/keplr-chain-registry/keplr-chain-registry/node_modules/@keplr-wallet/simple-fetch/src/fetch.ts:[9](https://github.com/chainapsis/keplr-chain-registry/actions/runs/7663995866/job/20890102483#step:7:10)6:11
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/keplr-chain-registry/keplr-chain-registry/node_modules/@keplr-wallet/simple-fetch/build/fetch.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  baseURL: 'https://api-testnet5.composable-cosmos.composablenodes.tech',
  url: '/cosmos/base/tendermint/v1beta1/node_info',
  response: {
    url: 'https://api-testnet5.composable-cosmos.composablenodes.tech/cosmos/base/tendermint/v1beta1/node_info',
    data: {
      code: 14,
      message: 'connection error: desc = "transport: Error while dialing: dial tcp [12](https://github.com/chainapsis/keplr-chain-registry/actions/runs/7663995866/job/20890102483#step:7:13)7.0.0.1:9091: connect: connection refused"',
      details: []
    },
    headers: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    },
    status: 503,
    statusText: 'Service Unavailable'
  }
}
Failed to get response /cosmos/base/tendermint/v1beta1/node_info from lcd endpoint
```

**Comment by JafarAz** [comment]
@HeesungB fixed, can you please try again

**Comment by HeesungB** [comment]
@JafarAz Could you fix typo?

`bansky-testnet/ppica.png` ->`banksy-testnet/ppica.png` 

```
Invalid image url: https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/bansky-testnet/ppica.png
```

**Comment by JafarAz** [comment]
@HeesungB apologies, took me a while to actually figure out what the typo was

**Comment by HeesungB** [comment]
@JafarAz Thank you for contribution!

**Pull request merged**
