### PR TITLE
add pstake logo

### PR DESCRIPTION
**Pull request by puneet2019**
- adds pstake logo
- adds pstake to gravity currencies
- adds pstake to core-1 fee-currency

### CODE REVIEW

**Comment by puneet2019** [comment]
@HeesungB can you take a look? Also lmk about if I can fix CI?

**Comment by HeesungB** [comment]
@puneet2019 Images can only be imported from directories with the same chain identifier.
So Could you add the pstake image to `images/core` as well, and name the image with the value `coinMinimalDenom`.

**Comment by puneet2019** [comment]
@HeesungB thank you, done!

**Comment by puneet2019** [comment]
@HeesungB can you let me know what's the issue now?

**Pull request merged**
