### PR TITLE
Add SNEAKY: A Stargaze native asset

### PR DESCRIPTION
**Pull request by thesneakydev**

### CODE REVIEW

**Comment by HeesungB** [comment]
@thesneakydev Please add an image like the link example below.

{chiainIdentifier}/{factory token minimal denom}/{minimal denom}.png

https://github.com/chainapsis/keplr-chain-registry/tree/main/images/osmosis/factory/osmo14klwqgkmackvx2tqa0trtg69dmy0nrg4ntq4gjgw2za4734r5seqjqm4gm

**Comment by thesneakydev** [comment]
> @thesneakydev Please add an image like the link example below.
> 
> {chiainIdentifier}/{factory token minimal denom}/{minimal denom}.png
> 
> https://github.com/chainapsis/keplr-chain-registry/tree/main/images/osmosis/factory/osmo14klwqgkmackvx2tqa0trtg69dmy0nrg4ntq4gjgw2za4734r5seqjqm4gm

@HeesungB SNEAKY is a native Stargaze asset. None of the other native Stargaze assets have an image in this format. Can you advise?

A {denom}.png has been added to images/stargaze directory like other Stargaze assets, but the images/osmosis directory doesn't contain any images for Stargaze assets in the format you requested.

Many thanks.

**Comment by HeesungB** [comment]
@thesneakydev Can you remove `images/stargaze/sneaky.png` image file?

**Comment by thesneakydev** [comment]
> @thesneakydev Can you remove `images/stargaze/sneaky.png` image file?

Done. 👍

**Comment by HeesungB** [comment]
@thesneakydev Thank you for contibution!

**Pull request merged**
