### PR TITLE
Add $KIRA token to Keplr Wallet

### PR DESCRIPTION
**Pull request by donluigi888**

### CODE REVIEW

**Comment by HeesungB** [comment]
@donluigi888 Hello. Please add an image like the link example below.

{chiainIdentifier}/{factory token minimal denom}/{minimal denom}.png

https://github.com/chainapsis/keplr-chain-registry/tree/main/images/osmosis/factory/osmo14klwqgkmackvx2tqa0trtg69dmy0nrg4ntq4gjgw2za4734r5seqjqm4gm

**Comment by donluigi888** [comment]
Hello, thank you for your answer. Just don't get how to add image to injective.json if image is still not added to the main branch? Should look like this "coinImageUrl": "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/injective/kira.png", no?

**Comment by donluigi888** [comment]
> @donluigi888 Hello. Please add an image like the link example below.
> 
> {chiainIdentifier}/{factory token minimal denom}/{minimal denom}.png
> 
> https://github.com/chainapsis/keplr-chain-registry/tree/main/images/osmosis/factory/osmo14klwqgkmackvx2tqa0trtg69dmy0nrg4ntq4gjgw2za4734r5seqjqm4gm

or do I have to add image in the above format? I wanted to add it like "inj" and "ninja" logo.

**Comment by HeesungB** [comment]
@donluigi888 This format is right `images/injective/factory/inj1xy3kvlr4q4wdd6lrelsrw2fk2ged0any44hhwq/KIRA.png`
so Could you remove `images/injective/KIRA.png` image file? 

and Could you resize image to 256x256px size?

**Comment by donluigi888** [comment]
> @donluigi888 This format is right `images/injective/factory/inj1xy3kvlr4q4wdd6lrelsrw2fk2ged0any44hhwq/KIRA.png` so Could you remove `images/injective/KIRA.png` image file?
> 
> and Could you resize image to 256x256px size?

Thank you, I have changed everything now.

**Pull request merged**
