### PR TITLE
create for test

### PR DESCRIPTION
**Pull request by goblocto**

### CODE REVIEW

**Comment by HeesungB** [comment]
@goblocto Is it just test?

**Comment by goblocto** [comment]
Hello. Yes

пн, 10 апр. 2023 г., 06:01 HeesungB ***@***.***>:

**Comment by HeesungB** [comment]
@goblocto 
You can check using yarn validate cosmos/Lumb.json command in local envirnoment

**Comment by HeesungB** [comment]
@goblocto I'm closing the PR because it's been sitting for too long, but if you need it, please open it or raise it again.

**Pull request closed without merging**
