### PR TITLE
Add Composable assets

### PR DESCRIPTION
**Pull request by JafarAz**
This PR will enable support for KSM and DOT to be transferred via Composable's IBC bridge to Polkadot on the Keplr wallet.

### CODE REVIEW

**Comment by fl-y** [comment]
Hi @HeesungB,
due to the fact that we're adding native Kusama and Polkadot which cannot be added to the chain registry in any normal way,
these assets will not be visible.

The KSM originates from Picasso parachain on the Kusama network after XCMing from Kusama
and DOT originates from the Composable parachain on the Polkadot network after XCMing from Polkadot.

The Centauri chain we're trying to add these assets to is the first Cosmos chain these assets arrive at
and given this context I think it will most likely be the least hassle for both parties
to add an exception for these assets if we want those to be visible in Keplr.

If you have any other suggestions to make these assets visible
happy to discuss alternative methods to make it work
thanks

**Comment by HeesungB** [comment]
@JafarAz @fl-y 
It looks like we need to check with an internal source to make sure it's okay.
Would you mind sending a small batch of those tokens to the address below?
This is our test account address.

```
centauri1wf87ctwh5pqwugr0x9vemcllyn7vu8q4pdkj9a
```

**Comment by fl-y** [comment]
> @JafarAz @fl-y It looks like we need to check with an internal source to make sure it's okay. Would you mind sending a small batch of those tokens to the address below? This is our test account address.
> 
> ```
> centauri1wf87ctwh5pqwugr0x9vemcllyn7vu8q4pdkj9a
> ```

Sorry for the late reply, we just sent 0.2DOT over
[89F13F81A610FA929B5D2BB4E49120F041C40E9A8E3DEBA83BC67DB325D6CBBC](https://explorer.nodestake.top/composable/tx/89F13F81A610FA929B5D2BB4E49120F041C40E9A8E3DEBA83BC67DB325D6CBBC)

**Comment by HeesungB** [comment]
@JafarAz @fl-y 
I got the coin and checked it out.
I checked the Keplr feature, but there may be a bug if I add it as it is, so I will stay after fixing the Keplr bug.

**Comment by JafarAz** [comment]
Hey @HeesungB hope you're well. Can we now merge this PR?

**Comment by HeesungB** [comment]
@JafarAz Could you resize image to 256x256px?

**Comment by JafarAz** [comment]
@HeesungB updated image sizes according to the requirements requested

**Comment by JafarAz** [comment]
@HeesungB any updates on pushing this PR forward sir?

**Comment by HeesungB** [comment]
@JafarAz Sorry. I forgot it.

**Pull request merged**
