### PR TITLE
Added image for bluzelle test network

### PR DESCRIPTION
**Pull request by njmurarka**
Will be adding config once this is approved.

### CODE REVIEW

**Comment by HeesungB** [comment]
@njmurarka Could you add json file in this pr?

**Comment by njmurarka** [comment]
Sure except it kept failing because the image was not already in the repo. Catch 22?

**Comment by njmurarka** [comment]
Added it. But check expects image to already be in the repo?

**Comment by njmurarka** [comment]
@HeesungB hopefully it is all in order and this PR can be approved. The issue is the JSON refers to the image URL as it will be, once the image (part of this PR) is actually added to the repo.

**Comment by njmurarka** [comment]
I am not sure if I need to do something else to resolve this. Please let me know. 

I am pretty sure the JSON link to the image is correct, provided the image itself gets approved as part of the PR.

**Comment by HeesungB** [comment]
@njmurarka Humm.. I will check it

**Comment by njmurarka** [comment]
> @njmurarka Humm.. I will check it

Ok thanks. Please let me know.

**Comment by HeesungB** [comment]
@njmurarka I think it's like a mainnet image and I can't read it.
How about change image url link `https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/bluzelle/chain.png`

or

How about change image file to a different image file than the main net?

**Comment by njmurarka** [comment]
@HeesungB Thanks!

I replaced the image for the testnet with a new image but checks failed again. Why does it keep saying it is an invalid URL?

**Comment by njmurarka** [comment]
Please let me know what I can do to make this pass?

**Comment by njmurarka** [comment]
@HeesungB Thanks! That resolved it. 

Please advise when this PR might get accepted.

**Comment by HeesungB** [comment]
@njmurarka
Could you remove `coinGeckoId` field??
I don't think the testnet token price should be tied to the mainnet token price.

**Comment by HeesungB** [comment]
@njmurarka Thank you for contribution!

**Comment by njmurarka** [comment]
Thanks!

**Pull request merged**
