### PR TITLE
feat: add union testnet

### PR DESCRIPTION
**Pull request by o-az**

### CODE REVIEW

**Comment by HeesungB** [comment]
@o-az Hello. 
Can you edit the file using the link below?
https://github.com/chainapsis/keplr-chain-registry#requirement-details

You can also use the command below to check the validation locally.
```
yarn validate cosmos/union-testnet.json
```

**Comment by o-az** [comment]
> @o-az Hello. Can you edit the file using the link below? [chainapsis/keplr-chain-registry#requirement-details](https://github.com/chainapsis/keplr-chain-registry#requirement-details)
> 
> You can also use the command below to check the validation locally.
> 
> ```
> yarn validate cosmos/union-testnet.json
> ```

@HeesungB I have 1 error remaining:
```sh
Invalid image url: https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/union/chain.png
```
It's not possible to solve this error unless it's merged. Should I provide a different url or does the image have to be hosted in the repo?

**Comment by o-az** [comment]
@HeesungB `yarn validate cosmos/union-testnet.json` passes now. Thank you for reviewing.

**Comment by o-az** [comment]
There's no coingecko id for `UNO` at the moment but this indicates it's a required value. Any suggestions @HeesungB?
https://github.com/chainapsis/keplr-chain-registry/actions/runs/7939150165/job/21707390769#step:7:1

**Pull request merged**
