### PR TITLE
Create ixo.json

### PR DESCRIPTION
**Pull request by alwyn-ixo**

### CODE REVIEW

**Comment by HeesungB** [comment]
And you have to add node provider information.

```json
 "nodeProvider": {
    "name": "Blockapsis",
    "email": "infra@blockapsis.com",
    "website":"https://blockapsis.com/"
  },
  ```

**Comment by alwyn-ixo** [comment]
> And you have to add node provider information.
> 
> ```json
>  "nodeProvider": {
>     "name": "Blockapsis",
>     "email": "infra@blockapsis.com",
>     "website":"https://blockapsis.com/"
>   },
> ```

do you suggest this node provider as a good option?

**Comment by HeesungB** [comment]
`ixo` is a native chain, so we will change your chain information

**Comment by HeesungB** [comment]
@alwyn-ixo 
Your chain information is updated.

In the `Keplr` wallet, if the chain ID changes, it is judged to be a `different chain`.
We upgraded the `Keplr` wallet extension with the changed chain ID and are reviewing it.

**Comment by alwyn-ixo** [comment]
Rather use the latest PR

**Pull request closed without merging**
