### PR TITLE
Added DOKI & MYRK to odin chain

### PR DESCRIPTION
**Pull request by AddySiz**

### CODE REVIEW

**Comment by HeesungB** [comment]
@AddySiz Could you remove `coingeckoId` field?

**Comment by AddySiz** [comment]
> @AddySiz Could you remove `coingeckoId` field?

Done

**Comment by HeesungB** [comment]
@AddySiz Could you remove `"coinType": 118` field?

**Comment by AddySiz** [comment]
> @AddySiz Could you remove `"coinType": 118` field?

Hi ! But ODIN by is default coinType:118
494 is an additional cointype that old users still need access to. That's why that option was included, too.

**Comment by HeesungB** [comment]
@AddySiz Yes, I know.

So inside the `bip44 field`, the `coinType` entry is the main cointype and the
inside the `alternativeBIP44s field` is the coinType sub-cointype.

But I was just asking you to remove the `cointype field` because it is not currently used.

```
 },
  "bip44": {
    "coinType": 118
  },
  "alternativeBIP44s": [
    {
      "coinType": 494
    }
  ],

 ...

 "coinType": 118
```

**Comment by AddySiz** [comment]
thanks @HeesungB 
did the required changes, Removed  "coin type": 118 from the end, and completed by adding missing logos, etc.

**Comment by HeesungB** [comment]
@AddySiz Could you resize image to `256x256px`?
```
Image size is not 256x256px. size : {"height":200,"width":200,"type":"png"}
```

**Comment by AddySiz** [comment]
Hi @HeesungB 
Logos updated to 256x256 px.

**Comment by HeesungB** [comment]
@AddySiz Could you rename coin image name to `coinMinimalDenom`?

**Review by Satchitananda — APPROVED** [review]
@AddySiz LGTM

**Comment by AddySiz** [comment]
@HeesungB Rename Done

**Comment by HeesungB** [comment]
@AddySiz Thank you for contribution.

**Pull request merged**
