### PR TITLE
Add Qwoyn Network Testnet

### PR DESCRIPTION
**Pull request by dpdanpittman**
This PR adds earendel-1 to the chain registry.

### CODE REVIEW

**Comment by dpdanpittman** [comment]
Sorry for all the commits, any updates I make I'll make sure and test locally first

**Comment by HeesungB** [comment]
@dpdanpittman Are you ready to merge?

**Comment by dpdanpittman** [comment]
Yes please

**Comment by HeesungB** [comment]
@dpdanpittman Thank you for contribution!

**Pull request merged**
