### PR TITLE
add dydx, usdc and stkdydx to fee currencies on persistence

### PR DESCRIPTION
**Pull request by saurabhfegade**

### CODE REVIEW

**Comment by saurabhfegade** [comment]
Waiting till 1:30 pm UTC, 15th Feb 2024 for persistence chain upgrade, post which the PR is ready to merge

**Comment by HeesungB** [comment]
@saurabhfegade Should I merge it?

**Comment by saurabhfegade** [comment]
hey @Thunnini any reason for reverting the commit?

**Comment by HeesungB** [comment]
@saurabhfegade There is a bug on Node

**Comment by saurabhfegade** [comment]
hey @HeesungB sorry can you please elaborate? Is there something we need to do from our side? We want to enable paying fees with DYDX, stkDYDX and USDC on persistence

also, have made another PR - #434 with gasPriceSteps adjusted accordingly for DYDX and stkDYDX since they have precision of 18 decimals

**Pull request merged**
