### PR TITLE
Update QWOYN gas prices

### PR DESCRIPTION
**Pull request by dpdanpittman**

### CODE REVIEW

**Comment by HeesungB** [comment]
@dpdanpittman Is there any documentation to base gas rate changes on?

**Comment by dpdanpittman** [comment]
Not specifically, no.  Is there a standard for calculating it?

**Comment by HeesungB** [comment]
@dpdanpittman 
If you look at the PRs here, they're usually moderated by a governance vote in the chain.
https://github.com/chainapsis/keplr-chain-registry/pull/284 https://github.com/chainapsis/keplr-chain-registry/pull/232

**Comment by dpdanpittman** [comment]
Oh hmm ok,  just keep the values I have.  They should work great.
Validators have all chosen 0.025uqwoyn as min gas fee.  Thanks

**Comment by dpdanpittman** [comment]
Thanks!

**Pull request merged**
