### PR TITLE
feat: add desmos chain

### PR DESCRIPTION
**Pull request by dadamu**

### CODE REVIEW

**Comment by HeesungB** [comment]
You can confirm that chain information file is correct through the command below.

```shell
# install node modules
yarn install

# validate your json file (ex. yarn validate cosmos/osmosis.json)
yarn validate {your-chain-identifer}.json 
```

**Comment by HeesungB** [comment]
Hi, thank you for your contribution! We highly appreciate it.

However, there are some parts that do not comply with the requirements
1. Please change file name to your chain-identifer
2. Please change image directory name to your chain-identifer

**Comment by dadamu** [comment]
@HeesungB Fixed. Thanks for the help!

**Comment by HeesungB** [comment]
@dadamu Hi, thank you for your contribution!

**Pull request merged**
