### PR TITLE
Request to add AssetMantle Chain

### PR DESCRIPTION
**Pull request by kombos**
added and verified, the chain config details and chain image for AssetMantle.

### CODE REVIEW

**Comment by HeesungB** [comment]
@kombos Thank you for contribution!

**Comment by kombos** [comment]
> @kombos Thank you for contribution!

could you please let us know when it will be updated in the keplr extension ? also currently there is an additional attribute (beta: true) that is coming during suggest chain. would that be removed once udpated ?

**Comment by HeesungB** [comment]
@kombos 
This repository used adding on this page(https://chains.keplr.app/)
If you want to add chain in Keplr, Could you contact the partnership department? https://keplr.crunch.help/en/

**Comment by kombos** [comment]
> @kombos This repository used adding on this page([chains.keplr.app](https://chains.keplr.app/)) If you want to add chain in Keplr, Could you contact the partnership department? [keplr.crunch.help/en](https://keplr.crunch.help/en/)

ok, also, in https://chains.keplr.app/ , can we make sure that the chain details show even if that chain is currently added to Keplr ?  have recorded this feature request here: 
https://github.com/chainapsis/keplr-chain-registry/issues/58

**Pull request merged**
