### PR TITLE
add BADDOG currency to chihuahua.json

### PR DESCRIPTION
**Pull request by SmolFatality**

### CODE REVIEW

**Comment by HeesungB** [comment]
@SmolFatality Please add an image like the link example below.

{chiainIdentifier}/{factory token minimal denom}/{minimal denom}.png

https://github.com/chainapsis/keplr-chain-registry/tree/main/images/osmosis/factory/osmo14klwqgkmackvx2tqa0trtg69dmy0nrg4ntq4gjgw2za4734r5seqjqm4gm

**Comment by SmolFatality** [comment]
Sorry was in the process and got sidetracked irl. Doing so now.

**Comment by SmolFatality** [comment]
Added correct sized img

**Comment by HeesungB** [comment]
@SmolFatality Can you move image file to `/images/chihuahua/factory/chihuahua1x4q2vkrz4dfgd9hcw0p5m2f2nuv2uqmt9xr8k2/achihuahuawifhat.png` location?

This is the factory token image storage rule.

**Comment by SmolFatality** [comment]
Yes

**Review by SmolFatality — COMMENTED** [review]
fixed image issue, sorry it took so long. Thanks for the review.

**Comment by SmolFatality** [comment]
@HeesungB

**Comment by HeesungB** [comment]
@SmolFatality Could you move image to `images/chihuahua/factory/chihuahua1x4q2vkrz4dfgd9hcw0p5m2f2nuv2uqmt9xr8k2/achihuahuawifhat.png`?

and You should change image's name.

**Comment by SmolFatality** [comment]
I thought I did that earlier. Let me double check.

**Comment by SmolFatality** [comment]
done

**Comment by HeesungB** [comment]
@SmolFatality Oh Could you add `factory` directory?
Your image file is in`images/chihuahua/chihuahua1x4q2vkrz4dfgd9hcw0p5m2f2nuv2uqmt9xr8k2/achihuahuawifhat.png`
But It will be in `images/chihuahua/factory/chihuahua1x4q2vkrz4dfgd9hcw0p5m2f2nuv2uqmt9xr8k2/achihuahuawifhat.png`

**Comment by SmolFatality** [comment]
@HeesungB man, i feel bad i had to annoy you too much. hopefully this is the last time.

**Comment by HeesungB** [comment]
@SmolFatality No It is okay! Thank you for contribution!

**Comment by HeesungB** [comment]
@SmolFatality You can do this by registering on coingecko and adding it here.

**Pull request merged**
