### PR TITLE
bump morocco-1, add 90u-2

### PR DESCRIPTION
**Pull request by discoverdefiteam**

### CODE REVIEW

**Comment by HeesungB** [comment]
@discoverdefiteam Hello.
Could you rename file name to `90u` from `90u-2`?

**Comment by discoverdefiteam** [comment]
@HeesungB hey there, the file name is currently `90u-2`, not too sure how to resolve this issue..

**Comment by discoverdefiteam** [comment]
ah, sorry completely misread that, will do that now!

**Comment by HeesungB** [comment]
@discoverdefiteam Fee Currency must be included in currencies.
Could you check your file?

**Comment by HeesungB** [comment]
@discoverdefiteam Could you remove `walletUrl` field?

**Comment by discoverdefiteam** [comment]
yep!

**Comment by discoverdefiteam** [comment]
@HeesungB , how do we set the test network name (Terp Testnet)? currently it is displaying the name as `terp`

**Comment by HeesungB** [comment]
@discoverdefiteam You can set `Terp Testnet`.
Could you check about [this link](https://github.com/chainapsis/keplr-chain-registry/blob/main/cosmos/axelar-testnet-lisbon.json)

**Comment by HeesungB** [comment]
@discoverdefiteam Should I merge it?

**Comment by discoverdefiteam** [comment]
please!

**Comment by HeesungB** [comment]
@discoverdefiteam Thank you for contribution!

**Comment by discoverdefiteam** [comment]
Thank you for you help :)

**Pull request merged**
