### PR TITLE
Add Pundi X Chain

### PR DESCRIPTION
**Pull request by zakir-code**

### CODE REVIEW

**Comment by HeesungB** [comment]
@zakir-code Hello.
Could you remove `walletUrlForStaking` field?
and You can not use ibc currency in currencies field. Could you replace currency?

**Comment by zakir-code** [comment]
@HeesungB Hi.
I have deleted walletUrlForStaking field.

Sorry, why can't we use ibc token? The bond denom currently used on the pundix chain is the PUNDIX token and mint denom is the PURSE token.
https://px-rest.pundix.com/cosmos/bank/v1beta1/denoms_metadata

```
{
  "metadatas": [
    {
      "description": "PURSE Token",
      "denom_units": [
        {
          "denom": "bsc0x29a63f4b209c29b4dc47f06ffa896f32667dad2c",
          "exponent": 0,
          "aliases": [ ]
        },
        {
          "denom": "PURSE",
          "exponent": 18,
          "aliases": [ ]
        }
      ],
      "base": "bsc0x29a63f4b209c29b4dc47f06ffa896f32667dad2c",
      "display": "PURSE",
      "name": "PURSE Token",
      "symbol": "PURSE"
    },
    {
      "description": "Pundi X Token",
      "denom_units": [
        {
          "denom": "ibc/55367b7b6572631b78a93c66ef9fdfce87cde372cc4ed7848da78c1eb1dcdd78",
          "exponent": 0,
          "aliases": [ ]
        },
        {
          "denom": "PUNDIX",
          "exponent": 18,
          "aliases": [ ]
        }
      ],
      "base": "ibc/55367b7b6572631b78a93c66ef9fdfce87cde372cc4ed7848da78c1eb1dcdd78",
      "display": "PUNDIX",
      "name": "Pundi X Token",
      "symbol": "PUNDIX"
    }
  ],
  "pagination": {
    "next_key": null,
    "total": "2"
  }
}
```

**Comment by malm0d** [comment]
Hi @HeesungB, we'd like to follow up on this. Is it not possible to use ibc currency in the currencies field?

Should we submit a new PR in this case?

**Comment by HeesungB** [comment]
@zakir-code @malm0d In its current structure, CURRENCIES cannot contain IBC tokens.

**Comment by zakir-code** [comment]
@HeesungB Is this possible if ibc token is removed from `currencies`?

**Pull request closed without merging**
