### PR TITLE
Update lum-network.json RPC urls

### PR DESCRIPTION
**Pull request by Segfaultd**
### Introduction

This little PR updates the public Lum Network's RPC urls following a recent infrastructure change, to ensure compatibility on Keplr wallet

### CODE REVIEW

**Comment by HeesungB** [comment]
@Segfaultd Hello.
Could you check your node?
```
Failed to connect websocket to /websocket rpc
```

**Comment by Segfaultd** [comment]
@HeesungB sure, the URL is actually not the default one, it is:

```ws://rpc.node0.mainnet.lum.network/wss/websocket```

**Comment by HeesungB** [comment]
@Segfaultd Use `/websocket` in the address of the RPC node.

**Comment by Segfaultd** [comment]
@HeesungB it's fixed!

**Pull request merged**
