### PR TITLE
Add oraichain

### PR DESCRIPTION
**Pull request by tucq88**
- [x] Add config for Oraichain
- [x] Add token ORAI
- [x] Add token ORAIX

### CODE REVIEW

**Comment by tucq88** [comment]
Can you please have a look @ducphamle2 ?

**Comment by HeesungB** [comment]
@tucq88 Hello.
Could you resize image to `256x256px`?
And Could you check chain id?
```
Chain identifier unmatched: (expected: Oraichain, actual: oraichain)
```

**Comment by HeesungB** [comment]
@tucq88 May I merge it?

**Comment by tucq88** [comment]
Yes please. Thanks you

**Pull request merged**
