### PR TITLE
[READY] add nibiru chain

### PR DESCRIPTION
**Pull request by Tocard**

### CODE REVIEW

**Comment by k-yang** [comment]
Thank you ❤️

**Comment by Tocard** [comment]
> Thank you ❤️

You're welcome, but could you provide email for nibiru ? this is the only one thing missing acutally :)

**Comment by cgilbe27** [comment]
> > Thank you ❤️
> 
> You're welcome, but could you provide email for nibiru ? this is the only one thing missing acutally :)

bugs@nibiru.org

**Comment by Tocard** [comment]
@HeesungB Do we need to build something or provide something ?

**Comment by HeesungB** [comment]
@Tocard Could you check chain identifier?
I think that your identifier is `nibiru-itn`, so You have to change your file name and image directory name to `nibiru-itn`

**Comment by HeesungB** [comment]
@sudopunk Hello. 
Can you edit the file using the link below?
https://github.com/chainapsis/keplr-chain-registry#requirement-details

You can also use the command below to check the validation locally.
```
yarn validate cosmos/nibiru-itn.json
```

**Comment by Tocard** [comment]
> @Tocard Could you check chain identifier? I think that your identifier is `nibiru-itn`, so You have to change your file name and image directory name to `nibiru-itn`

Maybe for mainnet, but for this testnet, this is nibiru-itn-3.

**Comment by HeesungB** [comment]
@Tocard I think you need to change your testnet chain ID.

**Comment by Tocard** [comment]
> @Tocard I think you need to change your testnet chain ID.

not sure to understand correctly what do you mean.

https://explorer.nibiru.fi/nibiru-itn-3/staking

chain id is nibiru-itn-3

```shell
chimera@moz:~$ nibiru --home /opt/chimera/nibiru/ config
{
        "chain-id": "nibiru-itn-3",
        "keyring-backend": "os",
        "output": "text",
        "node": "tcp://localhost:26657",
        "broadcast-mode": "sync"
}

```

```json
{
  "NodeInfo": {
    "protocol_version": {
      "p2p": "8",
      "block": "11",
      "app": "0"
    },
    "id": "358b55e0c6462b4c4f5f1551307a519296a91f8b",
    "listen_addr": "tcp://0.0.0.0:26656",
    "network": "nibiru-itn-3",
    "version": "0.37.2",
    "channels": "40202122233038606100",
    "moniker": "Chimera-Delta | LFDM",
    "other": {
      "tx_index": "on",
      "rpc_address": "tcp://127.0.0.1:26657"
    }
  },
  "SyncInfo": {
    "latest_block_hash": "AFAB84577303F3B01D58DE8EEA315F66FE2721A10512C2D79FA6A2140784EB0E",
    "latest_app_hash": "A025DF748FC0398F70F3DE2E88E7AEAD01CDCD226BCA5D11F23F0E7A097FE083",
    "latest_block_height": "355441",
    "latest_block_time": "2023-10-08T13:05:28.357961984Z",
    "earliest_block_hash": "0E175965E1A30546FA0EF5918B9B8019919B12FF34C4D4ADFFADEEE34AED89FC",
    "earliest_app_hash": "A8D78DFC09EAB1F31864DE7BC843AACAE8E14C98A2E5EE9EB64198F378F194B6",
    "earliest_block_height": "56001",
    "earliest_block_time": "2023-10-02T18:48:50.667164455Z",
    "catching_up": false
  },
  "ValidatorInfo": {
    "Address": "609F31922ABA8FFD7F34A32CE1C254B28776E7BE",
    "PubKey": {
      "type": "tendermint/PubKeyEd25519",
      "value": "TgZp8xFWoRpZ9spftaJnv6rhoj7x8mELQPrTTqastc4="
    },
    "VotingPower": "83"
  }
}

```

**Comment by HeesungB** [comment]
@Tocard 
The Keplr wallet uses the concept of a chain identifier internally. [[Link]](https://github.com/chainapsis/keplr-chain-registry#chain-registration-directory-structure)
`"chain-id": "nibiru-itn-3"` In this chain, `nibiru-itn` is the chain identifier.
This chain identifier cannot be overlapped.
Therefore, it is recommended that you specify a different chain identifier for your testnet.

**Comment by Tocard** [comment]
> @Tocard The Keplr wallet uses the concept of a chain identifier internally. [[Link]](https://github.com/chainapsis/keplr-chain-registry#chain-registration-directory-structure) `"chain-id": "nibiru-itn-3"` In this chain, `nibiru-itn` is the chain identifier. This chain identifier cannot be overlapped. Therefore, it is recommended that you specify a different chain identifier for your testnet.

done

**Comment by HeesungB** [comment]
@Tocard There are issues in your file.
so Can you edit the file using the link below?
https://github.com/chainapsis/keplr-chain-registry#requirement-details

You can also use the command below to check the validation locally.
```
yarn validate cosmos/nibiru-itn.json
```

**Comment by Tocard** [comment]
> @Tocard There are issues in your file. so Can you edit the file using the link below? https://github.com/chainapsis/keplr-chain-registry#requirement-details
> 
> You can also use the command below to check the validation locally.
> 
> ```
> yarn validate cosmos/nibiru-itn.json
> ```

Done

**Comment by HeesungB** [comment]
@Tocard Thank you for contribution!

**Pull request merged**
