### PR TITLE
add carbon evm info

### PR DESCRIPTION
**Pull request by randy75828**

### CODE REVIEW

**Comment by stevenkhong** [comment]
@editaahn bump, please help to merge this for Keplr wallet to work with [Carbon EVM](https://carbon.network).

**Comment by editaahn** [comment]
Hey, could you please wait until we update a certain part that could resolve a potential issue related to it? We'll be merging this change afterward, and let you know. Sorry for the inconvenience. @stevenkhong

**Comment by editaahn** [comment]
Please pull the changes from upstream to your forked registry and check the validation on `evm` passed! @stevenkhong

**Comment by randy75828** [comment]
@editaahn hi i have rebased my changes on the latest upstream commit and all checks have passed!

**Pull request merged**
