### PR TITLE
Add Odin protocol network

### PR DESCRIPTION
**Pull request by alvarogharo**

### CODE REVIEW

**Comment by HeesungB** [comment]
@alvarogharo Thank you for contribution!

**Comment by AddySiz** [comment]
@HeesungB, we've come across an issue we'd like to discuss regarding the coin type for Odin. Previously, some of our older user wallets were configured with coin `type 494`. However, since we've added Odin's information on keplr as default `coin-type 118`, it seems to restrict us from manually specifying 494 as the coin type. Could you possibly provide guidance on how we could overcome this issue? We appreciate your help; this will help our users who are no able to access 494 wallets.
Regards- Anant

**Comment by AddySiz** [comment]
> @HeesungB, we've come across an issue we'd like to discuss regarding the coin type for Odin. Previously, some of our older user wallets were configured with coin `type 494`. However, since we've added Odin's information on keplr as default `coin-type 118`, it seems to restrict us from manually specifying 494 as the coin type. Could you possibly provide guidance on how we could overcome this issue? We appreciate your help; this will help our users who are no able to access 494 wallets. Regards- Anant

@HeesungB it will be great to understand how can we go about adding the odin 494 coin type as well.

**Comment by AddySiz** [comment]
@Satchitananda FYI

**Comment by HeesungB** [comment]
@AddySiz Hello. Sorry to late reply.
I added `alternativeBIP44s` field that is for your case.
You can check below link.
https://github.com/chainapsis/keplr-chain-registry/commit/8801fcecbe36bd0391f849ad7e037f5512e05c79

By adding `alternativeBIP44s`, users will be able to select the coinType as shown in the photo below when adding their account by mnemonic.

스크린샷 2023-11-29 오후 12 51 13

**Pull request merged**
