### PR TITLE
Initial Keplr Wallet Integration

### PR DESCRIPTION
**Pull request by superphly**
Initial Andromeda Chain Integration

### CODE REVIEW

**Comment by HeesungB** [comment]
@superphly Hello.
Could you add node provider information?

**Comment by superphly** [comment]
Where can I find an example? I was having a hard time understanding the format and what was required. If there is a documentation link somewhere, that'd be helpful. Thanks!

**Comment by HeesungB** [comment]
@superphly 
I wanted to share a sample of the form we discussed. You can find it here: [Chain Registration Form](https://github.com/chainapsis/keplr-chain-registry#chain-registration-form)

Additionally, for more in-depth information on the requirements, check out: [Requirement Details](https://github.com/chainapsis/keplr-chain-registry#requirement-details)

**Comment by superphly** [comment]
One of our teammates submitted the update.

**Comment by HeesungB** [comment]
@superphly Could you remove `coinGeckoId` field?
I can't get price data on coingecko site.

**Comment by HeesungB** [comment]
@superphly Thank you for contribution!

**Pull request merged**
